package besmart;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Inventory implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private String description;

    private String no;

    public Inventory() {
    }
    
    public Inventory(String no, String description) {
        this.no = no;
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }

}