package bjb_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeModel implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private Integer age;

    private String idEmployee;

    private Integer score;

    public EmployeeModel() {
    }
    
    public EmployeeModel(String idEmployee, Integer age, Integer score) {
        this.idEmployee = idEmployee;
        this.age = age;
        this.score = score;
    }

    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    public String getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(String idEmployee) {
        this.idEmployee = idEmployee;
    }

    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }

}