package mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Bankruptcy implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private Integer amountOwed;

    private Integer yearOfOccurrence;

    public Bankruptcy() {
    }
    
    public Bankruptcy(Integer amountOwed, Integer yearOfOccurrence) {
        this.amountOwed = amountOwed;
        this.yearOfOccurrence = yearOfOccurrence;
    }

    public Integer getAmountOwed() {
        return this.amountOwed;
    }
    
    public void setAmountOwed(Integer amountOwed) {
        this.amountOwed = amountOwed;
    }

    public Integer getYearOfOccurrence() {
        return this.yearOfOccurrence;
    }
    
    public void setYearOfOccurrence(Integer yearOfOccurrence) {
        this.yearOfOccurrence = yearOfOccurrence;
    }

}